workspace 'Tencent_Effect_Ivs'

def amazonIVS
  platform :ios, '12.0'
  pod 'AmazonIVSBroadcast', '1.31.0'
#  pod 'TencentEffect_S1-01'
# 将S1-07替换成您购买的套餐
pod 'TEBeautyKit/S1-07', :podspec => 'https://mediacloud-76607.gzc.vod.tencent-cloud.com/TencentEffect/iOS/TEBeautyKit/latest/TEBeautyKit.podspec'
end

def amazonIVSStages
  platform :ios, '14.0'
  pod 'AmazonIVSBroadcast/Stages', '1.31.0'
end

target 'BasicBroadcast' do
  amazonIVS
end

target 'ScreenCapture' do
  platform :ios, '12.0'
  pod 'AmazonIVSBroadcast', '1.31.0'
end

target 'StagesApp' do
  amazonIVSStages
end
