# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/volcengine/volcengine-specs.git'
target 'Tencent_Effect_Byte' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tencent_Effect_Byte
  
  pod 'VolcEngineRTC', '3.60.102.5300'
  pod 'TEBeautyKit',:podspec => 'https://mediacloud-76607.gzc.vod.tencent-cloud.com/TencentEffect/iOS/TEBeautyKit/latest/TEBeautyKit.podspec'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
